# We have 2 stage Test and Deploy
stages:
  #  - test
  - build

# Config cache
cache:
  paths:
    - node_modules/

# Currently we have not tests :)
# Test job
#test:
#  # Docker image
#  image: node:latest
#  # Attach Test job to Test stage
#  stage: test
#  # Config to use GitLab Shared Runner with Executor Docker
#  tags:
#    - docker
#  script:
#    - npm install
#    - npm run test
#  # Defines the names of branches and tags the job runs for
#  only:
#    - master

# Deploy job
build:
  # Attach Deploy job to Deploy stage
  stage: build
  # Config to use our Runner with Executor Shell
  tags:
    - build
  script:
    # Only copy changed files to project folder
    - sudo cp -r -u * $PROJECT_DIR
    - cd $PROJECT_DIR
    - yarn install
    - yarn build
  only:
    - master
